VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemVendor" "Lenovo"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemProduct" "G50 80"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemVersion" "<empty>"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemSerial" "string:%random%"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemSKU" "string:%random%"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemFamily" "<empty>"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemUuid" "d18cce0e-44f9-4a74-808c-ff8ff99889da"

VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVendor" "Lenovo"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVersion" "string:%random%"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBIOSReleaseDate" "%SYSdate%"

VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardVendor" "Lenovo"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardProduct" "G50 80"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardVersion" "string:%random%"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardSerial" "string:%random%"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardAssetTag" "string:%random%"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardLocInChass" "<empty>"
VBoxManage setextradata "Vbox name" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardBoardType" "10"
